### ISSUE TITLE
What is GitHub?

### ISSUE THREAD

**Issue by schalkneethling** [The-Mycelium-Network/webworkbook#22]
Document what GitHub is and how it fits into the larger developer ecosystem. Also, find and write about alternatives to GitHub.

**Comment by samyaksand** [comment]
Hello, Im interested in working on this. Please assign me this issue.

**Comment by schalkneethling** [comment]
Hey @samyaksand, @JaiNeethling has already expressed interest in this one. I do believe there is another issue I assigned to you. If that is not the case, please let me know. Thanks!

**Comment by JaiNeethling** [comment]
I think I made it?

**Comment by bpires** [comment]
Leaving some GitHub official resources here for future reference:

- [GitHub Docs](https://docs.github.com/en)
- [GitHub Skills](https://skills.github.com/)
- [Git Cheat Sheets](https://training.github.com/)
- [GitHub Training & Guides](https://www.youtube.com/githubguides)

**Comment by bpires** [comment]
**I found some interesting stats you should consider including, if it makes sense:**

[Stack Overflow Developer Survey 2022](https://survey.stackoverflow.co/2022/#section-version-control-version-control-platforms) shows that GitHub remains the most popular version control hosting service, with 87% of respondents relying on it for personal use and 56%, for professional use.

GitLab and Bitbucket, the second and third most used services, come far behind, with, respectively, 21% and 11% adoption for personal use and 29% and 18% adoption for professional use. The survey also evidences that, except GitHub, the other services are more likely used for professional purposes instead of personal ones.

**Comment by schalkneethling** [comment]
> **I found some interesting stats you should consider including, if it makes sense:**
> 
> [Stack Overflow Developer Survey 2022](https://survey.stackoverflow.co/2022/#section-version-control-version-control-platforms) shows that GitHub remains the most popular version control hosting service, with 87% of respondents relying on it for personal use and 56%, for professional use.
> 
> GitLab and Bitbucket, the second and third most used services, come far behind, with, respectively, 21% and 11% adoption for personal use and 29% and 18% adoption for professional use. The survey also evidences that, except GitHub, the other services are more likely used for professional purposes instead of personal ones.

This is good information, thanks @bpires. I am going to create an issue from your suggestion here.
